# Generated by Django 4.2.21 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveauEtude', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('etablissementOrigine', models.CharField(max_length=200)),
                ('concoursSouhaiter', models.CharField(choices=[('licence_twin', 'LICENCE TWIN'), ('licence_srit', 'LICENCE SRIT'), ('master_informatique', 'MASTER INFORMATIQUE')], max_length=150)),
                ('extraitNaissance', models.FileField(upload_to='documents/extrait/')),
                ('certificatNationalite', models.FileField(upload_to='documents/certificat/')),
                ('lettreMotivation', models.FileField(upload_to='documents/lettre/')),
                ('diplome', models.FileField(upload_to='documents/diplome/')),
                ('photo', models.ImageField(upload_to='documents/photo')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('numero_inscription', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
