# Generated by Django 4.2.21 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='certificatNationalite',
            new_name='certificat_nationalite',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='concoursSouhaiter',
            new_name='concours_souhaiter',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='etablissementOrigine',
            new_name='etablissement_origine',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='extraitNaissance',
            new_name='extrait_naissance',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='lettreMotivation',
            new_name='lettre_motivation',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='niveauEtude',
            new_name='niveau_etude',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='photo',
            field=models.ImageField(upload_to='documents/photo/'),
        ),
    ]
