# Generated by Django 4.2.21 on 2025-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_rename_certificatnationalite_inscription_certificat_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
